### ISSUE TITLE
打包的时候能注意一下警告么?

### ISSUE THREAD

**Issue by ghost** [GetuiLaboratory/getui-sdk-ios-cocoapods#11]
我使用的个推1.5.3版本

有10个这样的Warning
warning: /var/folders/nm/y29gjrfd64b8b8y0cgx5hhbc0000gn/C/org.llvm.clang.zhaowei/ModuleCache/2VU6G8UDA25RM/CoreFoundation-271U74KHGUIO4.pcm: No such file or directory
静态库Release的时候把Enable module debug 选项关了,OK?

**Comment by WcZhaoWei** [comment]
新版本已经修改
