### ISSUE TITLE
请提供2.4.6 的noidfa版本

### ISSUE THREAD

**Issue by zhiliang729** [GetuiLaboratory/getui-sdk-ios-cocoapods#14]

**Comment by aklee** [comment]
建议使用pod最新版本。
如果需要单独下载个别版本，可以至官网URL下载。如：https://www.getui.com/download/docs/getui/iOS/GETUI_IOS_SDK_2.4.6.0.zip

格式为：
https://www.getui.com/download/docs/getui/iOS/GETUI_IOS_SDK_你需要的版本号.zip
