### ISSUE TITLE
2.6.0.0上传到App Store处理失败

### ISSUE THREAD

**Issue by yinanwang1** [GetuiLaboratory/getui-sdk-ios-cocoapods#19]
错误信息：
ITMS-90562: Invalid Bundle - The app cannot be processed because options not allowed to be embedded in bitcode are detected in the submission. It is likely that you are not building the app with the toolchain provided in Xcode. Rebuild your entire app with the latest GM Xcode and submit the app again.

把版本将会2.5.9.0后，处理成功了。

**Comment by yinanwang1** [comment]
2.6.1.0版本包一样的错误。
ITMS-90562: Invalid Bundle - The app cannot be processed because options not allowed to be embedded in bitcode are detected in the submission. It is likely that you are not building the app with the toolchain provided in Xcode. Rebuild your entire app with the latest GM Xcode and submit the app again.

**Comment by huqx-getui** [comment]
Dear developer:
Please update to 2.6.2.0
