### ISSUE TITLE
低级警告修复

### ISSUE THREAD

**Issue by di1688** [GetuiLaboratory/getui-sdk-ios-cocoapods#2]
能修复包里面的低级警告吗？

while processing /Users/zrh/Documents/app-ios/Pods/GTSDK/libGeTuiSdk-1.4.2.a(GTXAppenderManager.o):
warning: /var/folders/_k/7t70yqjd7cv2mgtf6j0ltxfc0000gn/C/org.llvm.clang.gexin/ModuleCache/1OMS5IXFPHADG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: Module debugging should be disabled when shipping static libraries.
while processing /Users/zrh/Documents/app-ios/Pods/GTSDK/libGeTuiSdk-1.4.2.a(GTXAppenderManager.o):
warning: /var/folders/_k/7t70yqjd7cv2mgtf6j0ltxfc0000gn/C/org.llvm.clang.gexin/ModuleCache/1OMS5IXFPHADG/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Users/zrh/Documents/app-ios/Pods/GTSDK/libGeTuiSdk-1.4.2.a(GTXAppenderManager.o):
warning: /var/folders/_k/7t70yqjd7cv2mgtf6j0ltxfc0000gn/C/org.llvm.clang.gexin/ModuleCache/1OMS5IXFPHADG/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/zrh/Documents/app-ios/Pods/GTSDK/libGeTuiSdk-1.4.2.a(GTXReachability.o):
warning: /var/folders/_k/7t70yqjd7cv2mgtf6j0ltxfc0000gn/C/org.llvm.clang.gexin/ModuleCache/1OMS5IXFPHADG/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
while processing /Users/zrh/Documents/app-ios/Pods/GTSDK/libGeTuiSdk-1.4.2.a(GTXReachability.o):
warning: /var/folders/_k/7t70yqjd7cv2mgtf6j0ltxfc0000gn/C/org.llvm.clang.gexin/ModuleCache/1OMS5IXFPHADG/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
while processing /Users/zrh/Documents/app-ios/Pods/GTSDK/libGeTuiSdk-1.4.2.a(GTXReachability.o):
warning: /var/folders/_k/7t70yqjd7cv2mgtf6j0ltxfc0000gn/C/org.llvm.clang.gexin/ModuleCache/1OMS5IXFPHADG/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
while processing /Users/zrh/Documents/app-ios/Pods/GTSDK/libGeTuiSdk-1.4.2.a(GTXCaptureTool.o):
warning: /var/folders/_k/7t70yqjd7cv2mgtf6j0ltxfc0000gn/C/org.llvm.clang.gexin/ModuleCache/1OMS5IXFPHADG/CoreGraphics-N94D31PLFESQ.pcm: No such file or directory
while processing /Users/zrh/Documents/app-ios/Pods/GTSDK/libGeTuiSdk-1.4.2.a(GTXCryptoTool.o):
warning: /var/folders/_k/7t70yqjd7cv2mgtf6j0ltxfc0000gn/C/org.llvm.clang.gexin/ModuleCache/1OMS5IXFPHADG/Security-T0W5HZGV3ZZ1.pcm: No such file or directory

**Comment by WcZhaoWei** [comment]
解决方法：
1、Build Settings ——>Build Options——>Debug Information Format
2、Debug下的DWARF with dsYM File改成DWARF
3、Release下的还是之前默认的DWARF with dsYM File不变
