### ISSUE TITLE
YYModel 重复告警，可以兼容下吗？

### ISSUE THREAD

**Issue by ieliwb** [GetuiLaboratory/getui-sdk-ios-cocoapods#20]
pod 'YYModel'
pod 'GTSDK'
一片警告，自己去掉YYModel，项目找不到文件，可以适配下吗

**Comment by xiangBiaoOne** [comment]
我也遇到了同样的问题....
ld: warning: method '+arrayWithJSON:' in category from 
Pods/ZXSDK/ZXSDK.framework/ZXSDK(ZXSDKModel.o) conflicts with same method from another category
ld: warning: method '+arrayWithJSONData:' in category from

**Comment by aklee** [comment]
已反馈ZXSDK

**Comment by aklee** [comment]
fixed

**Comment by ieliwb** [comment]
pod update了，好像没有解决啊，还是警告哦
