### ISSUE TITLE
版本号为不符合版本号语义标准，无法通过版本号的方式指定引用

### ISSUE THREAD

**Issue by sugarwyc** [GetuiLaboratory/getui-sdk-ios-cocoapods#21]
![image](https://user-images.githubusercontent.com/5518603/212611380-8cb8c628-2213-4b4a-bebc-89039943240b.png)

版本号不符合[版本号语义标准](https://semver.org/)，无法通过版本号的方式指定引用

**Comment by GetuiLab** [comment]
Dear开发者：
您好，您可以通过个推官网，添加个推的技术支持，通过企业微信来给您解答该问题呢




support
***@***.***





---- 回复的原邮件 ----
发件人 ***@***.***>发送日期 2023年01月16日 14:25收件人 ***@***.***>抄送人 ***@***.***>主题 [GetuiLaboratory/getui-sdk-ios-cocoapods] 版本号为不符合版本号语义标准，无法通过版本号的方式指定引用 (Issue #21)


版本号不符合版本号语义标准，无法通过版本号的方式指定引用

**Comment by aklee** [comment]
SwiftPackgerManager 可以直接指定master分支即可

**Comment by sugarwyc** [comment]
> SwiftPackgerManager 可以直接指定master分支即可

需要引用特定版本，像这样：
```swift
.package(url: "https://github.com/GetuiLaboratory/getui-sdk-ios-cocoapods.git", exact: "2.7.3.0-noidfa")
```

**Comment by sugarwyc** [comment]
> > SwiftPackgerManager 可以直接指定master分支即可
> 
> 需要引用特定版本，像这样：
> 
> ```swift
> .package(url: "https://github.com/GetuiLaboratory/getui-sdk-ios-cocoapods.git", exact: "2.7.3.0-noidfa")
> ```

暂时可以这样解决：
```swift
.package(url: "https://github.com/GetuiLaboratory/getui-sdk-ios-cocoapods.git", revision: "90650faf00d233af263c8f0ee1f489e01d279074")
```

但还是希望后续能优化下，支持以版本号标签的方式引用

**Comment by sugarwyc** [comment]
只需要新建符合版本语义标准的标签就可以解决问题，例如：
- `2.7.3` --> `2.7.3.0`
- `2.7.3-noidfa ` --> `2.7.3.0-noidfa`
- `2.7.3-1` --> `2.7.3.1`
- `2.7.3-1-noidfa`  --> `2.7.3.1-noidfa`

```swift
dependencies: [
        .package(url: "https://github.com/sugarwyc/getui-sdk-ios-cocoapods.git", exact: "2.7.3-noidfa"),
]
```

**Comment by sugarwyc** [comment]
已解决，可以用`branch`指定：
```swift
.package(url: "https://github.com/GetuiLaboratory/getui-sdk-ios-cocoapods.git", branch: "2.7.3.0-noidfa")
```
