### ISSUE TITLE
[GtSdkManager destroyForSdk] 闪退

### ISSUE THREAD

**Issue by wuxie8** [GetuiLaboratory/getui-sdk-ios-cocoapods#22]
版本 'GTSDK' , '2.4.1.0-noidfa' #推送sdk sdk内部闪退
<img width="837" alt="截屏2023-02-20 18 32 35" src="https://user-images.githubusercontent.com/16465779/220081098-a7c6368b-1ad3-4069-97ed-7a9f4be7257f.png">

**Comment by GetuiLab** [comment]
麻烦访问个推官网，加一下个推的技术支持企业微信咨询！


support
***@***.***





---- 回复的原邮件 ----
发件人 ***@***.***>发送日期 2023年02月20日 18:33收件人 ***@***.***>抄送人 ***@***.***>主题 [GetuiLaboratory/getui-sdk-ios-cocoapods] [GtSdkManager destroyForSdk] 闪退 (Issue #22)

版本 'GTSDK' , '2.4.1.0-noidfa' #推送sdk sdk内部闪退

**Comment by aklee** [comment]
需要升级最新sdk版本

**Comment by aklee** [comment]
由于苹果已陆续不再支持GCDAsyncSocket库(会引入如上crash）， GTSDK在高版本iOS系统上将使用Network.framework进行通信。
苹果官方回复：https://developer.apple.com/forums/thread/707658
