### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by yuanshuainiuniu** [GetuiLaboratory/getui-sdk-ios-cocoapods#23]
版本：2.7.4.0
堆栈：
Exception Type: EXC_BREAKPOINT (SIGTRAP)

Exception Codes: KERN_INVALID_ADDRESS at 0x0000000105c17034

Crashed Thread: 49

Thread 49 Crashed:

0 XXX 0x0000000105c17034 closure #1 (Swift.Optional<Foundation.Data>, Swift.Optional<Network.NWConnection.ContentContext>, Swift.Bool, Swift.Optional<Network.NWError>) -> () in GbdSdk_.NetworkTcpUtil.(setupReceiveData in _884D766FA8E03EAA2E72044D8521917C)() -> () (in XXX) + 1624

1 XXX 0x0000000105c16ed0 closure #1 (Swift.Optional<Foundation.Data>, Swift.Optional<Network.NWConnection.ContentContext>, Swift.Bool, Swift.Optional<Network.NWError>) -> () in GbdSdk_.NetworkTcpUtil.(setupReceiveData in _884D766FA8E03EAA2E72044D8521917C)() -> () (in XXX) + 1268

2 libswiftNetwork.dylib 0x00000001d7d85040 closure #1 (Swift.Optional<__C.OS_dispatch_data>, Swift.Optional<__C.OS_nw_content_context>, Swift.Bool, Swift.Optional<__C.OS_nw_error>) -> () in Network.NWConnection.receiveMessage(completion: (Swift.Optional<Foundation.Data>, Swift.Optional<Network.NWConnection.ContentContext>, Swift.Bool, Swift.Optional<Network.NWError>) -> ()) -> () (in libswiftNetwork.dylib) + 168

3 libswiftNetwork.dylib 0x00000001d7d84c90 reabstraction thunk helper from @escaping @callee_guaranteed (@guaranteed Swift.Optional<__C.OS_dispatch_data>, @guaranteed Swift.Optional<__C.OS_nw_content_context>, @unowned Swift.Bool, @guaranteed Swift.Optional<__C.OS_nw_error>) -> () to @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<__C.OS_dispatch_data>, @unowned Swift.Optional<__C.OS_nw_content_context>, @unowned Swift.Bool, @unowned Swift.Optional<__C.OS_nw_error>) -> () (in libswiftNetwork.dylib) + 108

4 libdispatch.dylib 0x00000001c4000114 __dispatch_block_async_invoke2 (in libdispatch.dylib) + 148

5 libdispatch.dylib 0x00000001c3ff0fdc __dispatch_client_callout (in libdispatch.dylib) + 20

6 libdispatch.dylib 0x00000001c4002b8c __dispatch_root_queue_drain (in libdispatch.dylib) + 684

7 libdispatch.dylib 0x00000001c4003284 __dispatch_worker_thread2 (in libdispatch.dylib) + 164

8 libsystem_pthread.dylib 0x000000020aa65dbc __pthread_wqthread (in libsystem_pthread.dylib) + 228

**Comment by aklee** [comment]
请升级最新版本
