### ISSUE TITLE
Xcode 15 Beta 8、iOS 16.6 crash

### ISSUE THREAD

**Issue by Dwarven** [GetuiLaboratory/getui-sdk-ios-cocoapods#25]
![image](https://github.com/GetuiLaboratory/getui-sdk-ios-cocoapods/assets/5902224/4c828e65-8470-480f-a9e8-7331b3a1b0c0)

**Comment by yinanwang1** [comment]
The same question to me in the Xcode 15.
<img width="344" alt="image" src="https://github.com/GetuiLaboratory/getui-sdk-ios-cocoapods/assets/6257935/f5a711d8-56b9-4ef1-9e55-ee56927ea049">

**Comment by aklee** [comment]
项目的最低iOS版本需要改为12及以上，例子：设置成iOS 11会产生crash.  Xcode15 最低支持iOS 12.
具体原因及apple论坛反馈：https://developer.apple.com/forums/thread/737672

**Comment by yinanwang1** [comment]
> 项目的最低iOS版本需要改为12及以上，例子：设置成iOS 11会产生crash. Xcode15 最低支持iOS 12. 具体原因及apple论坛反馈：https://developer.apple.com/forums/thread/737672

嗯嗯。 设置成iOS12，问题解决了。
