### ISSUE TITLE
warnings: .pcm: No such file or directory

### ISSUE THREAD

**Issue by gknows** [GetuiLaboratory/getui-sdk-ios-cocoapods#4]
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/2CU2DKZ06QD2L/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/AVFoundation-2W8OQOO5E005V.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/MapKit-THDG17AXS092.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/AdSupport-N94D31PLFESQ.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/CoreTelephony-E0K26IE3JFHL.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/CoreBluetooth-14O21S15A37HY.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/CoreLocation-2RB9TGORWT0YQ.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/JavaScriptCore-N94D31PLFESQ.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/100AUKYLSMXVN/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/100AUKYLSMXVN/Security-T0W5HZGV3ZZ1.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/100AUKYLSMXVN/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/100AUKYLSMXVN/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/100AUKYLSMXVN/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/CoreGraphics-N94D31PLFESQ.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/CFNetwork-3188M7OK0JW08.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/2CU2DKZ06QD2L/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/2CU2DKZ06QD2L/MachO-1BMJAO5Q3NM3O.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/2CU2DKZ06QD2L/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/2CU2DKZ06QD2L/CoreGraphics-N94D31PLFESQ.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/2CU2DKZ06QD2L/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
warning: /Users/gexin/Library/Developer/Xcode/DerivedData/ModuleCache/1OMS5IXFPHADG/Security-T0W5HZGV3ZZ1.pcm: No such file or directory

**Comment by WcZhaoWei** [comment]
解决方法：
1、Build Settings ——>Build Options——>Debug Information Format
2、Debug下的DWARF with dsYM File改成DWARF
3、Release下的还是之前默认的DWARF with dsYM File不变
