### ISSUE TITLE
为什么要使用‘ CoreBluetooth’框架？

### ISSUE THREAD

**Issue by al03** [GetuiLaboratory/getui-sdk-ios-cocoapods#7]
为什么在`GTSDK.podspec` 加入了对`CoreBluetooth` 的依赖？

> s.frameworks = 'SystemConfiguration', 'CFNetwork','CoreTelephony','CoreLocation','AVFoundation','CoreBluetooth','Security','JavaScriptCore'
 > s.ios.frameworks = 'SystemConfiguration', 'CFNetwork','CoreTelephony','CoreLocation','AVFoundation','CoreBluetooth','Security','JavaScriptCore'

还有`CoreLocation`的依赖，麻烦说明下，个推哪些模块需要这些框架？😡

**Comment by WcZhaoWei** [comment]
之前版本中需要蓝牙辅助定位，实现地理围栏推送功能，在下个模块中将去除CoreBluetooth依赖

**Comment by al03** [comment]
@WcZhaoWei 因为在提交app到iTunes Connect时，如果没有在app plist里声明蓝牙权限描述的话会被reject。

**Comment by WcZhaoWei** [comment]
该问题是苹果iOS10后新出现的问题，我们最新的1.5.3中已经去除CoreBluetooth依赖，不在需要申明蓝牙权限描述

**Comment by al03** [comment]
OK.
