### ISSUE TITLE
GeTui iOS SDK 1.5.3 ,在 Mac 10.11 ， Xcode7.3 上报错

### ISSUE THREAD

**Issue by RoshanDev** [GetuiLaboratory/getui-sdk-ios-cocoapods#9]
[demo](https://github.com/RoshanDev/GeTuiTest)
![image](https://cloud.githubusercontent.com/assets/4354429/21449667/af9ca5be-c92a-11e6-89ff-e2224099292b.png)

**Comment by WcZhaoWei** [comment]
删除UserNotification就可以了，UserNotification是Xcode8才有的

**Comment by RoshanDev** [comment]
😳这个。。。我锁定了 1.5.0 版本。没找到 UserNotification 啊
![image](https://cloud.githubusercontent.com/assets/4354429/21511883/0d082be2-cce1-11e6-8aba-b430f4bc30a0.png)

**Comment by WcZhaoWei** [comment]
根据图片上显示，你下载的是1.5.3 版本，不是1.5.0，1.5.3 Demo包含UserNotification

**Comment by RoshanDev** [comment]
额，我的意思是我在公司项目里面暂时锁定了 1.5.0 版本。Xcode 7.3 也可以用了。但是这个 GeTuiTest 项目里面用到的确实是 1.5.3 ，没有找到您说的 UserNotification 。而且我是直接用 pod install 安装的额。
![image](https://cloud.githubusercontent.com/assets/4354429/21512067/9724a740-cce3-11e6-8125-7f0926e578ff.png)
